name: Release

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch: {}

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # to create GitHub Releases and upload assets
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Compile (bundle + copy assets)
        run: npm run compile

      - name: Package VSIX
        run: npx vsce package

      - name: Generate changelog for this release
        run: |
          npx conventional-changelog -p angular -r 1 -o CHANGELOG_RELEASE.md
          echo "Generated release changelog:" && head -n 50 CHANGELOG_RELEASE.md || true

      - name: Upload artifact (VSIX)
        uses: actions/upload-artifact@v4
        with:
          name: vsix
          path: |
            *.vsix
            CHANGELOG_RELEASE.md

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            *.vsix
            CHANGELOG_RELEASE.md
          body_path: CHANGELOG_RELEASE.md
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish to Open VSX (optional)
        if: ${{ env.OVSX_TOKEN != '' }}
        env:
          OVSX_TOKEN: ${{ secrets.OVSX_TOKEN }}
        run: npx ovsx publish -p "$OVSX_TOKEN"
